stages:
  - build
  - deploy

variables:
  DOCKER_REGISTRY: berkayb0306
  APP_NAME: nodejs-express-mysql-app
  KUBE_CONFIG: ${KUBE_CONFIG}

build:
  stage: build
  script:
    - docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}
    - docker build -t $DOCKER_REGISTRY/$APP_NAME:$CI_COMMIT_SHA .
    - docker tag $DOCKER_REGISTRY/$APP_NAME:$CI_COMMIT_SHA $DOCKER_REGISTRY/$APP_NAME:latest
    - docker push $DOCKER_REGISTRY/$APP_NAME:$CI_COMMIT_SHA
    - docker push $DOCKER_REGISTRY/$APP_NAME:latest
  only:
    - main
    - staging

deploy-staging:
  stage: deploy
  script:
    - echo "${KUBE_CONFIG}" > kubeconfig.yaml
    - export KUBECONFIG=kubeconfig.yaml
    - helm dependency update ./helm
    - helm upgrade --install $APP_NAME-staging ./helm
      --namespace staging
      --create-namespace
      --set image.tag=$CI_COMMIT_SHA
      --values helm/values-staging.yaml
  environment:
    name: staging
  only:
    - staging

deploy-production:
  stage: deploy
  script:
    - echo "${KUBE_CONFIG}" > kubeconfig.yaml
    - export KUBECONFIG=kubeconfig.yaml
    - helm dependency update ./helm
    - helm upgrade --install $APP_NAME-prod ./helm
      --namespace production
      --create-namespace
      --set image.tag=$CI_COMMIT_SHA
      --values helm/values-production.yaml
  environment:
    name: production
  only:
    - main
  when: manual
