apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nodejs-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/berkayb0306/nodejs-express-mysql.git  # GitHub repo URL'nizi buraya yazın
    targetRevision: main
    path: app-chart
    helm:
      valueFiles:
        - values-production.yaml
      parameters:
        - name: "image.tag"
          value: latest
  destination:
    server: https://kubernetes.default.svc
    namespace: production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
