apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: secretstore-sample
spec:
  provider:
    # Bu kısmı kullandığınız secret provider'a göre düzenleyin
    # Örnek: AWS Secrets Manager
    aws:
      service: SecretsManager
      region: eu-central-1
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: awssm-secret
            key: access-key
          secretAccessKeySecretRef:
            name: awssm-secret
            key: secret-key
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mysql-credentials
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: secretstore-sample
    kind: SecretStore
  target:
    name: mysql-credentials
  data:
    - secretKey: username
      remoteRef:
        key: prod/mysql/username
    - secretKey: password
      remoteRef:
        key: prod/mysql/password
    - secretKey: database
      remoteRef:
        key: prod/mysql/database
    - secretKey: host
      remoteRef:
        key: prod/mysql/host
