apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: default
type: Opaque
data:
  MYSQL_USER: bXl1c2Vy            # Base64 encoded "myuser"
  MYSQL_PASSWORD: QmVya2F5XzE5OTk= # Base64 encoded "Berkay_1999"
  MYSQL_ROOT_PASSWORD: cm9vdF9zZWN1cmUxMjM= # Base64 encoded "root_secure123"
