apiVersion: v1
kind: Secret
metadata:
  name: mysql-credentials
  namespace: default
type: Opaque
data:
  host: bXlzcWw=             # Base64 encoded "mysql"
  username: bXl1c2Vy          # Base64 encoded "myuser"
  password: QmVya2F5XzE5OTk=  # Base64 encoded "Berkay_1999"
  mysql-root-password: cm9vdHBhc3N3b3Jk  # Base64 encoded "rootpassword"
  mysql-password: QmVya2F5XzE5OTk=       # Base64 encoded "Berkay_1999"
