apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  MYSQL_USER: YmVya2F5X3NveTE5QGhvdG1haWwuY29t # Base64 encoded 'berkay_soy19@hotmail.com'
  MYSQL_PASSWORD: QmVya2F5XzE5OTk=             # Base64 encoded 'Berkay_1999'
