apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdHBhc3N3b3Jk  # 'rootpassword' base64 encoded
  MYSQL_USER: dXNlcg==                    # 'user' base64 encoded
  MYSQL_PASSWORD: cGFzc3dvcmQ=            # 'password' base64 encoded
