apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mysql-secrets
  namespace: production
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: kubernetes-secret-store
    kind: ClusterSecretStore
  target:
    name: mysql-secrets
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: mysql-credentials-prod
        property: username
    - secretKey: password
      remoteRef:
        key: mysql-credentials-prod
        property: password
    - secretKey: database
      remoteRef:
        key: mysql-credentials-prod
        property: database
    - secretKey: host
      remoteRef:
        key: mysql-credentials-prod
        property: host
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mysql-secrets
  namespace: staging
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: kubernetes-secret-store
    kind: ClusterSecretStore
  target:
    name: mysql-secrets
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: mysql-credentials-staging
        property: username
    - secretKey: password
      remoteRef:
        key: mysql-credentials-staging
        property: password
    - secretKey: database
      remoteRef:
        key: mysql-credentials-staging
        property: database
    - secretKey: host
      remoteRef:
        key: mysql-credentials-staging
        property: host
