apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mysql-credentials-prod
  namespace: production
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: secretstore-production
  target:
    name: mysql-credentials-prod
    creationPolicy: Owner
  data:
    - secretKey: mysql-root-password
      remoteRef:
        key: mysql-prod/root-password
    - secretKey: mysql-password
      remoteRef:
        key: mysql-prod/user-password
    - secretKey: mysql-replication-password
      remoteRef:
        key: mysql-prod/replication-password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mysql-credentials-staging
  namespace: staging
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: secretstore-staging
  target:
    name: mysql-credentials-staging
    creationPolicy: Owner
  data:
    - secretKey: mysql-root-password
      remoteRef:
        key: mysql-staging/root-password
    - secretKey: mysql-password
      remoteRef:
        key: mysql-staging/user-password
    - secretKey: mysql-replication-password
      remoteRef:
        key: mysql-staging/replication-password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mysql-secrets
  namespace: production
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: mysql-secret-store
    kind: SecretStore
  target:
    name: mysql-secrets
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: mysql-credentials-prod
        property: username
    - secretKey: password
      remoteRef:
        key: mysql-credentials-prod
        property: password
    - secretKey: database
      remoteRef:
        key: mysql-credentials-prod
        property: database
    - secretKey: host
      remoteRef:
        key: mysql-credentials-prod
        property: host
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mysql-secrets
  namespace: staging
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: mysql-secret-store
    kind: SecretStore
  target:
    name: mysql-secrets
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: mysql-credentials-staging
        property: username
    - secretKey: password
      remoteRef:
        key: mysql-credentials-staging
        property: password
    - secretKey: database
      remoteRef:
        key: mysql-credentials-staging
        property: database
    - secretKey: host
      remoteRef:
        key: mysql-credentials-staging
        property: host
