apiVersion: v1
kind: Secret
metadata:
  name: mysql-credentials-prod
  namespace: production
type: Opaque
data:
  username: bXl1c2Vy
  password: QmVya2F5XzE5OTk=
  database: bXlkYl9wcm9k
  host: bXlzcWwucHJvZHVjdGlvbg==
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-credentials-staging
  namespace: staging
type: Opaque
data:
  username: bXl1c2Vy
  password: QmVya2F5XzE5OTk=
  database: bXlkYl9zdGFnaW5n
  host: bXlzcWwuc3RhZ2luZw==
---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: kubernetes-secret-store
spec:
  provider:
    kubernetes:
      server:
        url: "https://kubernetes.default.svc"
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          namespace: external-secrets
          key: ca.crt
