apiVersion: v2
name: nodejs-express-mysql
description: A Helm chart for Node.js Express MySQL application
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: mysql
    version: "9.x.x"
    repository: "https://charts.bitnami.com/bitnami"
    condition: mysql.enabled
