name: CI Pipeline for Node.js App

on:
  push:
    branches:
      - main
      - staging

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install Dependencies
      run: npm install

    - name: Docker Login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker Image
      run: |
        docker build -t berkayb0306/nodejs-express-mysql-app:latest .

    - name: Push Docker Image to Docker Hub
      run: |
        docker push berkayb0306/nodejs-express-mysql-app:latest

    - name: Create Kind Cluster
      uses: helm/kind-action@v1.8.0
      with:
        config: k8s/kind-cluster.yaml
        cluster_name: my-cluster

    - name: Get Cluster Info
      run: |
        kubectl cluster-info
        kubectl get nodes -o wide
        kubectl get pods -A

    - name: Deploy to Kubernetes
      run: kubectl apply -f k8s/ --validate=false
