name: CI Pipeline for Node.js App

on:
  push:
    branches:
      - main
      - staging

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install Dependencies
      run: npm install

    - name: Docker Login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker Image
      run: |
        docker build -t berkayb0306/nodejs-express-mysql-app:latest .

    - name: Push Docker Image to Docker Hub
      run: |
        docker push berkayb0306/nodejs-express-mysql-app:latest

    - name: Create .kube directory
      run: |
        mkdir -p ~/.kube

    - name: Setup kubeconfig
      run: |
        echo "${{ secrets.KUBECONFIG_FILE }}" | base64 -d > ~/.kube/config
        chmod 600 ~/.kube/config

    - name: Install kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Test Kubernetes Connection
      run: kubectl cluster-info

    - name: Deploy to Kubernetes
      run: kubectl apply -f k8s/ --validate=false
