name: CI Pipeline for Node.js App

on:
  push:
    branches:
      - main
      - staging

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Kodu Checkout Et
    - name: Checkout Code
      uses: actions/checkout@v3

    # 2. Node.js Kurulumu
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    # 3. Bağımlılıkları Yükle
    - name: Install Dependencies
      run: npm install

    # 5. Docker Login
    - name: Docker Login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # 6. Docker Build
    - name: Build Docker Image
      run: |
        docker build -t berkayb0306/nodejs-express-mysql-app:latest .

    # 7. Docker Push
    - name: Push Docker Image to Docker Hub
      run: |
        docker push berkayb0306/nodejs-express-mysql-app:latest
