name: CI/CD Pipeline for Node.js App

on:
  push:
    branches:
      - main
      - staging
  pull_request:
    branches:
      - main
      - staging

env:
  REGISTRY: docker.io
  IMAGE_NAME: berkayb0306/nodejs-express-mysql-app

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set Environment Variables
        run: |
          if [[ ${{ github.ref }} == 'refs/heads/main' ]]; then
            echo "ENV=prod" >> $GITHUB_ENV
            echo "TAG=latest" >> $GITHUB_ENV
          else
            echo "ENV=staging" >> $GITHUB_ENV
            echo "TAG=staging" >> $GITHUB_ENV
          fi

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/main' && 'production' || 'staging' }}
    
    steps:
      - uses: actions/checkout@v3

      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'
          
      - name: Setup Kubeconfig
        run: |
          echo "${{ secrets.KUBECONFIG_FILE }}" | base64 -d > kubeconfig.yaml
          echo "KUBECONFIG=$(pwd)/kubeconfig.yaml" >> $GITHUB_ENV
          
      - name: Update Application Image
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            kubectl --kubeconfig=kubeconfig.yaml set image deployment/nodejs-express-mysql nodejs-express-mysql=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.TAG }} -n nodejs-express-mysql
          else
            kubectl --kubeconfig=kubeconfig.yaml set image deployment/nodejs-express-mysql nodejs-express-mysql=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.TAG }} -n nodejs-express-mysql
          fi
          
      - name: Wait for rollout
        run: |
          kubectl --kubeconfig=kubeconfig.yaml rollout status deployment/nodejs-express-mysql -n nodejs-express-mysql --timeout=120s
